apiVersion: v1
kind: Pod
metadata:
  name: hammerdb-pod-1
  namespace: hammer-db-ns
spec:
  containers:
  - name: hammerdb-pod-1
    image: sanran/hammerdb:v4.6-working
    command: 
      - "sleep"
      - "604800"
    resources:
      requests:
        memory: "1G"
        cpu: "1000m"
      limits:
        memory: "1G"
        cpu: "1000m"
    imagePullPolicy: IfNotPresent
